/* @flow */
'use strict';

export const SETTLEDSTART = 'SETTLEDSTART';
export const SETTLEDCOMPLETE = 'SETTLEDCOMPLETE';
export const UNSETTLEDSTART = 'UNSETTLEDSTART';
export const UNSETTLEDCOMPLETE = 'UNSETTLEDCOMPLETE';
export const SELECTCUSTOMER = 'SELECTCUSTOMER';
